# qcar_supervisor/config/ekf.yaml

# physical parameter
model_length: 2.5

# process‐noise vector (6 states: vx, vy, r, bg, bax, bay)
Q: [0.01,  0.01,  0.001,  1e-6,  1e-6,  1e-6]

# IMU measurement noise (2 channels: accel‐bias+vel, yaw‐rate)
R_imu: [0.2,  0.2]

