imu_topic: "/imu"
joint_states_topic: "/qcar/joint_states"
odom_topic: "/qcar/ekf/odom"
drive_wheel_joints: ["wheelfl_motor", "wheelfr_motor"]

odom_frame: "odom"
base_frame: "base_link"
publish_tf: true

# Initial pose (match spawn)
init_x: -4.3
init_y: 3.0
init_yaw: -3.14

# Process noise (continuous-time variances) [X,Y,psi,v,r,bg,ba]
q: [1.0e-12, 1.0e-12, 1.0e-10, 1.0e-10, 1.0e-6, 1.0e-10, 1.0e-10]

# Measurement noise (stdev)
gyro_std: 0.001
speed_std: 0.001

# Accelerometer handling
gravity_mode: "off"
startup_calib_time: 0.0
imu_lpf_hz: 15.0

# Wheel / timing
rw: 0.033
dtMaxEst: 0.01
